/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Preferences = IDL.Record({
  'recentTools' : IDL.Vec(IDL.Text),
  'darkMode' : IDL.Bool,
  'sessionMetadata' : IDL.Opt(
    IDL.Record({ 'fileName' : IDL.Text, 'pageCount' : IDL.Nat })
  ),
});

export const idlService = IDL.Service({
  'getPreferences' : IDL.Func([], [Preferences], ['query']),
  'setPreferences' : IDL.Func([Preferences], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Preferences = IDL.Record({
    'recentTools' : IDL.Vec(IDL.Text),
    'darkMode' : IDL.Bool,
    'sessionMetadata' : IDL.Opt(
      IDL.Record({ 'fileName' : IDL.Text, 'pageCount' : IDL.Nat })
    ),
  });
  
  return IDL.Service({
    'getPreferences' : IDL.Func([], [Preferences], ['query']),
    'setPreferences' : IDL.Func([Preferences], [], []),
  });
};

export const init = ({ IDL }) => { return []; };